name: Main workflow

on:
  push:

jobs:
  merge-master-to-develop:
    name: Merge branch1 and branch2 -> branch1-branch2
    runs-on: ubuntu-latest

    steps:
        - uses: peterjgrainger/action-create-branch@v2.2.0
          env:
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
          with:
            branch: 'branch1-branch2'
        - uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            source-branch: branch1
            target-branch: branch1-branch2
        - uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            source-branch: branch2
            target-branch: branch1-branch2
            
        - uses: devops-infra/action-pull-request@v0.4.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            source_branch: branch1-branch2
            target_branch: main
            title: My bundle
