name: Main workflow

on:
  push:

jobs:
  merge-master-to-develop:
    name: Merge branch5 and branch6 -> branch5-branch6
    runs-on: ubuntu-latest

    steps:
        - uses: peterjgrainger/action-create-branch@v2.2.0
          env:
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
          with:
            branch: 'branch5-branch6'
        - uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            source-branch: branch5
            target-branch: branch5-branch6
        - uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            source-branch: branch6
            target-branch: branch5-branch6
