name: Main workflow

on:
  push:

jobs:
  merge-master-to-develop:
    name: Merge branch1 and branch2 -> branch1-branch2
    runs-on: ubuntu-latest

    steps:
        - uses: peterjgrainger/action-create-branch@v2.2.0
          env:
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
          with:
            branch: 'branch3-branch4'
        - uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            source-branch: branch3
            target-branch: branch3-branch4
        - uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            source-branch: branch4
            target-branch: branch3-branch4
